# Generated by Django 4.1.3 on 2022-11-29 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=13)),
                ('course', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=70)),
                ('reg_no', models.CharField(max_length=14)),
                ('year', models.CharField(max_length=12)),
                ('semester', models.CharField(max_length=1)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Students-Dps/')),
                ('is_student', models.BooleanField(default=False, editable=False)),
                ('is_prefect', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['reg_no'],
            },
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=14)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Lecturer-Dps/')),
                ('is_lecturer', models.BooleanField(default=False, editable=False)),
                ('unit', models.CharField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('lec', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lecturers',
                'ordering': ['lec'],
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.CharField(editable=False, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('unit', models.CharField(max_length=70)),
                ('document', models.FileField(upload_to='Assignments/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
                'ordering': ['-uploaded'],
            },
        ),
    ]
